const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
let dataset=[], versions=[{time:'当前运行 · 2026-09-08 14:32',algo:'V29 初始基准',params:'Kc 0.25 · tauI 48.0 s · tauD 0 s',state:'运行中'}];
const presets={fixed:{kp:.25,ti:48,td:0},k_only:{kp:.20,ti:48,td:0},taui_only:{kp:.25,ti:57.6,td:0},full:{kp:.2,ti:62.5968,td:0}};
function makeDemo(n=700){return Array.from({length:n},(_,i)=>{const sp=50+(i>120?12:0)+(i>390?-7:0);const transient=(i>120?Math.exp(-(i-120)/50)*Math.sin((i-120)/15)*5:0)+(i>390?Math.exp(-(i-390)/45)*Math.sin((i-390)/14)*-3:0);return{time:i,sp,pv:sp-1.2+transient+Math.sin(i/29)*.5,mv:42+(sp-50)*1.4+transient*2+Math.sin(i/17)*1.8}})}
function parseCSV(text){const rows=text.trim().split(/\r?\n/).map(r=>r.split(/,|;|\t/));if(rows.length<3)throw Error('数据行不足');const h=rows[0].map(x=>x.trim().toLowerCase());const find=names=>h.findIndex(x=>names.some(n=>x===n||x.includes(n)));const ti=find(['time','时间','timestamp']),si=find(['sp','setpoint','设定值']),pi=find(['pv','process','过程值']),mi=find(['mv','output','控制量']);if(si<0||pi<0)throw Error('未找到 SP/PV 列');return rows.slice(1).map((r,i)=>({time:+r[ti]||i,sp:+r[si],pv:+r[pi],mv:mi>=0?+r[mi]:0})).filter(r=>Number.isFinite(r.sp)&&Number.isFinite(r.pv)).slice(0,12000)}
function draw(data=dataset){const c=$('#scopeCanvas'),ctx=c.getContext('2d'),dpr=devicePixelRatio||1,w=c.clientWidth,h=c.clientHeight;c.width=w*dpr;c.height=h*dpr;ctx.scale(dpr,dpr);ctx.clearRect(0,0,w,h);if(!data.length)return;const step=Math.max(1,Math.ceil(data.length/w)),sample=data.filter((_,i)=>i%step===0);const vals=sample.flatMap(d=>[d.sp,d.pv,d.mv]).filter(Number.isFinite),min=Math.min(...vals),max=Math.max(...vals),pad=(max-min)*.12||1;const plot=(key,color,width=1.5)=>{ctx.beginPath();sample.forEach((d,i)=>{const x=i/(sample.length-1)*w,y=h-(d[key]-min+pad)/(max-min+2*pad)*h;i?ctx.lineTo(x,y):ctx.moveTo(x,y)});ctx.strokeStyle=color;ctx.lineWidth=width;ctx.stroke()};plot('mv','#55a6ff',1);plot('sp','#ffb84a',1.4);plot('pv','#35d4d0',2)}
function analyze(data){if(!data.length)return;const e=data.map(d=>Math.abs(d.sp-d.pv)),rmse=Math.sqrt(data.reduce((s,d)=>s+(d.sp-d.pv)**2,0)/data.length),iae=e.reduce((a,b)=>a+b,0),mean=e.reduce((a,b)=>a+b,0)/e.length,score=Math.max(45,Math.min(96,Math.round(94-rmse*9-mean*2)));$('#sampleCount').textContent=data.length.toLocaleString();$('#iae').textContent=iae.toFixed(2);$('#rmse').textContent=rmse.toFixed(3);$('#healthScore').textContent=score;$('#trackVal').textContent=Math.min(96,score+6)+'%';$('#scoreSummary').textContent=score>80?'回路跟踪稳定，可进一步优化响应速度':'存在可优化空间，建议检查滞后与振荡';draw(data)}
function toast(msg){const t=$('#toast');t.textContent=msg;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),2600)}
function loadFile(file,source){if(!file)return;const reader=new FileReader();reader.onload=()=>{try{dataset=parseCSV(reader.result);analyze(dataset);if(source==='eval'){$('#evalState').innerHTML=`<span class="good">${file.name}</span><small>${dataset.length.toLocaleString()} 个有效点</small>`}else{$('#tuneFileName').textContent=`已载入 ${file.name} · ${dataset.length.toLocaleString()} 点`;if(typeof clearStageResultsForNewData==='function')clearStageResultsForNewData()}toast(source==='tune'?'数据解析完成；等待 V30 服务返回新的逐阶段 PID':'数据解析完成，性能指标已更新')}catch(e){toast('读取失败：'+e.message)}};reader.readAsText(file)}
$$('[data-file]').forEach(b=>b.onclick=()=>$('#'+b.dataset.file).click());$('#evalFile').onchange=e=>loadFile(e.target.files[0],'eval');$('#tuneFile').onchange=e=>loadFile(e.target.files[0],'tune');['evalDrop','tuneDrop'].forEach(id=>{const el=$('#'+id);el.ondragover=e=>{e.preventDefault();el.classList.add('drag')};el.ondragleave=()=>el.classList.remove('drag');el.ondrop=e=>{e.preventDefault();el.classList.remove('drag');loadFile(e.dataTransfer.files[0],id==='evalDrop'?'eval':'tune')}});
$$('input[name=algo]').forEach(r=>r.onchange=()=>{$$('.algo').forEach(x=>x.classList.toggle('selected',x.contains(r)&&r.checked));const p=presets[r.value];$('#kp').value=p.kp;$('#ti').value=p.ti;$('#td').value=p.td;toast('已查看 V29 模式候选参数')});
const modelFits={arx421:['4','2 samples','3.0'],arx321:['3','2 samples','3.0'],arx221:['2','2 samples','3.0']};$$('input[name=model]').forEach(r=>r.onchange=()=>{$$('.process-model').forEach(x=>x.classList.toggle('selected',x.contains(r)&&r.checked));const m=modelFits[r.value];$('#modelK').textContent=m[0];$('#modelTau').textContent=m[1];$('#modelDelay').textContent=m[2];toast('已查看 V29 模型候选；最终选择由开发集误差决定')});
function renderHistory(){const box=$('#historyRows');box.innerHTML=versions.map((v,i)=>`<div class="tr"><span>${v.time}</span><span>${v.algo}</span><span>${v.params}</span><span><i class="status-chip">${v.state}</i></span><button data-rollback="${i}">${i===0?'查看':'回退'}</button></div>`).join('');$$('[data-rollback]').forEach(b=>b.onclick=()=>rollback(+b.dataset.rollback))}
function rollback(i){const v=versions[i];if(!v)return;const nums=v.params.match(/[\d.]+/g);if(nums?.length>=3){$('#kp').value=nums[0];$('#ti').value=nums[1];$('#td').value=nums[2]}toast('已恢复该版本参数，尚未下发');location.hash='tuning'}
$('#applyBtn').onclick=()=>{const name=$('input[name=algo]:checked').closest('.algo').querySelector('strong').textContent;versions.unshift({time:'待应用 · '+new Date().toLocaleString('zh-CN',{hour12:false}),algo:name,params:`Kp ${$('#kp').value} · Ti ${$('#ti').value} s · Td ${$('#td').value} s`,state:'待确认'});renderHistory();toast('建议参数已加入版本记录，可随时回退')};$('#saveBtn').onclick=()=>toast('方案已保存到本地版本记录');$('#recalcBtn').onclick=()=>{analyze(dataset);toast('已依据当前数据重新计算')};$('#rollbackLatest').onclick=()=>rollback(Math.min(1,versions.length-1));$('#demoBtn').onclick=()=>{dataset=makeDemo();analyze(dataset);$('#evalState').innerHTML='<span class="good">demo_loop_FIC201.csv</span><small>700 个有效点</small>';$('#tuneFileName').textContent='复用性能评估数据 · demo_loop_FIC201.csv';toast('示例数据已载入')};$('#exportBtn').onclick=()=>{const text=`PID 回路诊断报告\n综合评分: ${$('#healthScore').textContent}/100\nIAE: ${$('#iae').textContent}\nRMSE: ${$('#rmse').textContent}\n建议: Kp ${$('#kp').value}, Ti ${$('#ti').value}, Td ${$('#td').value}`;const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([text],{type:'text/plain;charset=utf-8'}));a.download='PID诊断报告.txt';a.click();URL.revokeObjectURL(a.href)};$$('.nav-btn').forEach(b=>b.onclick=()=>{$$('.nav-btn').forEach(x=>x.classList.remove('active'));b.classList.add('active');$('#'+b.dataset.target).scrollIntoView()});window.onresize=()=>draw();dataset=makeDemo();analyze(dataset);renderHistory();
